id: I22917AB5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T01:37:59+00:00'
last_modified: '2022-06-08T10:59:19.886991+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18126
  title: ས་བཅོས་ཀྱི་གདོན་གྲོལ་རིགས་ལྔ་ནད་སྤོར་དུག་དབྱུང་དང་བཅས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4330':
      image_group_id: I8LS18151
      title: ''
      total_pages: 24
      order: 1
      base_file: 4330.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
