id: P009431
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS18126
  title: ས་བཅོས་ཀྱི་གདོན་གྲོལ་རིགས་ལྔ་ནད་སྤོར་དུག་དབྱུང་དང་བཅས་པ།
  author: ''
  volumes:
    a5ee67a18a11498c847d713f30dfea07:
      image_group_id: I8LS18151
      title: ''
      volume_number: 1
      total_pages: 24
      base_file: v001.txt
